#!/bin/sh

sudo pacman -S --needed git base-devel

if ! type yay; then
    git clone https://aur.archlinux.org/yay.git
    cd ./yay
    makepkg -si
    cd $HOME
    rm -rf ./yay
fi

yay -S --needed - < ~/.config/pkglist.txt

if ! [ -d ~/.emacs.d ]; then
   git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
   ~/.emacs.d/bin/doom install 
fi

if ! [ -d ~/.ghcup ]; then
    curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
fi
